k3s_version: "v1.36.2+k3s1"
token: "{{ lookup('community.general.onepassword', 'testlab - k3s cluster token', field='password', vault='Home Network') }}"
api_endpoint: "{{ hostvars[groups['server'][0]]['ansible_host'] | default(groups['server'][0]) }}"
