[env]
_.file = ".env"

[tools]
opentofu = "1.12"
1password-cli = "latest"

[tasks."op:whoami"]
description = "test that OP_SERVICE_ACCOUNT_TOKEN auth works"
run = "op whoami"

[tasks."op:read"]
description = "read a secret from 1Password, e.g. mise run op:read -- op://vault/item/field"
run = "op read"

[tasks."tofu:core:init"]
description = "tofu init for tofu/core, wiring up the pg backend config"
dir = "{{config_root}}/infrastructure/core"
run = "tofu init -backend-config=backend.hcl"

[tasks."tofu:core:plan"]
description = "tofu plan for tofu/core"
dir = "{{config_root}}/infrastructure/core"
run = "tofu plan"

[tasks."tofu:core:apply"]
description = "tofu apply for tofu/core"
dir = "{{config_root}}/infrastructure/core"
run = "tofu apply"

[tasks."tofu:core:fmt"]
description = "check tofu/testbed formatting and modify files"
dir = "{{config_root}}/infrastructure/core"
run = "tofu fmt -diff -recursive"

[tasks."tofu:core:fmt-check"]
description = "check tofu/core formatting without modifying files"
dir = "{{config_root}}/infrastructure/core"
run = "tofu fmt -check -diff -recursive"

[tasks."tofu:core:validate"]
description = "validate tofu/core config"
dir = "{{config_root}}/infrastructure/core"
run = "tofu validate"

[tasks."tofu:core:check"]
description = "check formatting and validity of tofu/core configs"
depends = [
  "tofu:core:fmt-check",
  "tofu:core:validate",
]

[tasks."tofu:testbed:init"]
description = "tofu init for tofu/testbed, wiring up the pg backend config"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu init -backend-config=backend.hcl"

[tasks."tofu:testbed:plan"]
description = "tofu plan for tofu/testbed"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu plan"

[tasks."tofu:testbed:apply"]
description = "tofu apply for tofu/testbed"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu apply"

[tasks."tofu:testbed:fmt"]
description = "check tofu/testbed formatting without modifying files"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu fmt -diff -recursive"

[tasks."tofu:testbed:fmt-check"]
description = "check tofu/testbed formatting and modify files"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu fmt -check -diff -recursive"

[tasks."tofu:testbed:validate"]
description = "validate tofu/testbed config"
dir = "{{config_root}}/infrastructure/testbed"
run = "tofu validate"

[tasks."tofu:testbed:check"]
description = "check formatting and validity of tofu/testbed configs"
depends = [
  "tofu:testbed:fmt-check",
  "tofu:testbed:validate",
]

[tasks."tofu:fmt"]
description = "check formatting modify files for all tofu configs"
depends = [
  "tofu:core:fmt",
  "tofu:testbed:fmt",
]

[tasks."tofu:check"]
description = "check formatting and validity of all tofu configs"
depends = [
  "tofu:core:check",
  "tofu:testbed:check",
]
