---
apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: snapdrop
spec:
  interval: 30m
  chartRef:
    kind: OCIRepository
    name: snapdrop

  values:
    persistence:
      config:
        size: 1Gi
