info:
  name: reconfigure
  type: http
  seq: 2

http:
  method: POST
  url: http://{{api_url}}/api/kea/service/reconfigure
  auth: inherit

settings:
  encodeUrl: true
  timeout: 0
  followRedirects: true
  maxRedirects: 5
