apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: volsync-restic-repo
spec:
  storageClassName: nfs-backups
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 50Gi
