- name: Install/Enable storage tools (nfs/iscsi)
  hosts: k3s_cluster
  become: true
  tasks:
    - name: Install nfs-common for NFS-backed persistent storage
      ansible.builtin.apt:
        name: nfs-common
        state: present
        update_cache: true
    - name: Install open-iscsi for Longhorn
      ansible.builtin.apt:
        name: open-iscsi
        state: present
    - name: Ensure iscsid is enabled and running for Longhorn
      ansible.builtin.systemd:
        name: iscsid
        enabled: true
        state: started
