---
apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: snapdrop
spec:
  interval: 10m
  prune: true
  wait: true
  timeout: 5m
  targetNamespace: default

  path: ./kubernetes/testlab/apps/default/snapdrop/app
  sourceRef:
    kind: GitRepository
    name: flux-system
    namespace: flux-system

  dependsOn:
    - name: gateway
      namespace: kube-system
