testbed:
  children:
    k3s_nodes:
      children:
        k3s_controllers:
          hosts:
            k3s_controller:
              ansible_host: 10.30.10.102

        k3s_workers:
          hosts:
            k3s_worker_0:
              ansible_host: 10.30.10.100
            k3s_worker_1:
              ansible_host: 10.30.10.101

