---
apiVersion: external-secrets.io/v1
kind: ExternalSecret
metadata:
  name: "${APP}-restic-b2"
spec:
  secretStoreRef:
    kind: ClusterSecretStore
    name: onepassword
  target:
    name: "${APP}-restic-b2"
    template:
      engineVersion: v2
      data:
        RESTIC_REPOSITORY: "s3:s3.${VOLSYNC_B2_REGION}.backblazeb2.com/${VOLSYNC_B2_BUCKET:=storage-homelab-theforce}/${VOLSYNC_B2_PATH:=k8s-backups-testlab}/${APP}"
        RESTIC_PASSWORD: "{{ .resticPassword }}"
        AWS_ACCESS_KEY_ID: "{{ .keyID }}"
        AWS_SECRET_ACCESS_KEY: "{{ .applicationKey }}"
  dataFrom:
    - extract:
        key: "Backblaze - Application Key - k8s-testlab"
