---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationSource
metadata:
  name: "${APP}"
spec:
  sourcePVC: "${VOLSYNC_PVC:=${APP}}"
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=0 4 * * *}" # 4AM daily
  rsyncTLS:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Direct}"
    address: "volsync-rsync-tls-dst-${APP}-dst.${VOLSYNC_NAMESPACE}.svc.cluster.local"
    keySecret: "volsync-rsync-tls-${APP}-dst"
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
