---
apiVersion: volsync.backube/v1alpha1
kind: ReplicationDestination
metadata:
  name: "${APP}-dst"
spec:
  trigger:
    schedule: "${VOLSYNC_SCHEDULE:=0 4 * * *}" # 4AM daily
  rsyncTLS:
    copyMethod: "${VOLSYNC_COPYMETHOD:=Direct}"
    destinationPVC: "${VOLSYNC_PVC:=${APP}}"
    storageClassName: "${VOLSYNC_STORAGECLASS:=nfs-backups}"
    accessModes: ["${VOLSYNC_ACCESSMODES:=ReadWriteOnce}"]
    capacity: "${VOLSYNC_CAPACITY:=5Gi}"
    serviceType: ClusterIP
    moverSecurityContext:
      runAsUser: ${VOLSYNC_PUID:=1000}
      runAsGroup: ${VOLSYNC_PGID:=1000}
      fsGroup: ${VOLSYNC_PGID:=1000}
